### ISSUE TITLE
Caption in Lightbox/Fancybox/etc.

### ISSUE THREAD

**Issue by renatkina** [nitsan-technologies/ns_all_lightbox#1]
How can I get an Imagecaption into a Lightbox/Fancybox/etc.? Thank you.

**Comment by nitsan-technologies** [comment]
Hi @renatkina,

Thank you for your suggestion.

This functionality was not present in this extension.
We have adapted this Image Caption functionality and uploaded a new version of this extension[3.1.0] at TER.
You can download this updated extension either from this repository or from TER.
**TER:** https://extensions.typo3.org/extension/ns_all_lightbox/
**Repository:** https://github.com/nitsan-technologies/ns_all_lightbox/

Now, the caption will be rendered from this field (https://i.imgur.com/UQlXila.png, https://i.imgur.com/ohtXe4z.png).

Let us know if you have any query :)

Cheers!

**Comment by renatkina** [comment]
Hi,
Wow! Thank you so much!!! You are great!
Cheers!

NITSAN Technologies <notifications@github.com> schrieb am Mi., 24. Apr.
2019, 14:58:
