### ISSUE TITLE
Remove / change automatic js inclusion done by extension?

### ISSUE THREAD

**Issue by baden32** [nitsan-technologies/ns_all_lightbox#2]
Hi Sanjay, 
Could you let me know how it's possiblle to remove or change the code inserted at the end of the page :

		<script type='text/javascript'>
			$(document).ready(function() {
				$(".fancybox").fancybox();
			});
		</script>

I need to use my own code, because I add in ex. a $(a.fancybox.iframe).xxx instruction.
Thank y ou in advance for your help.
Joel

**Comment by nitsan-technologies** [comment]
Hey @baden32 

Sorry for the delayed reply.

Yes, You can use your own code.
For that, you need to change in this file.

**For TYPO3 7**
**Path:** EXT:ns_all_lightbox/Configuration/TypoScript/TYPO3-7/fancybox2.txt

**For TYPO3 8,9**
**Path:** EXT:ns_all_lightbox/Configuration/TypoScript/TYPO3/fancybox2.txt

Let us know if you have any queries or suggestions :)

Cheers:
