### ISSUE TITLE
Does not work with special characters (Umlaute)

### ISSUE THREAD

**Issue by bihor** [nitsan-technologies/ns_all_lightbox#4]
When there is a file like "danke_für_alles.jpg" than I get this error, when this extension is active:

(1/2) #1509741907 TYPO3Fluid\Fluid\Core\ViewHelper\Exception

Folder "/user_upload/mitmachen/danke_f%C3%BCr_alles.jpg/" does not exist.

Solution: change this line:
`<a href='<f:uri.image src="{file.publicUrl}" maxWidth="{settings.media.popup.width}" maxHeight="{settings.media.popup.height}" />' rel='lightbox[grup{data.uid}]' data-title="{file.description}">`
to
`<a href='<f:uri.image src="{file.uid}" treatIdAsReference="1" maxWidth="{settings.media.popup.width}" maxHeight="{settings.media.popup.height}" />' rel='lightbox[grup{data.uid}]' data-title="{file.description}">`

**Comment by lukasdoerr** [comment]
+1 still not updated
EDIT: Thanks to @bihor - his fix works fine :) !

**Comment by nitsan-technologies** [comment]
Dear @bihor 

Thanks for the solution, we have just released your patch in v4.2.1 https://extensions.typo3.org/extension/ns_all_lightbox

Cheers!
