### ISSUE TITLE
Proper cms-core requirements in composer.json

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [nitsan-technologies/ns_all_lightbox#8]
Hi,

since 23. December 2021 this extensions reqeuires TYPO3 core 7.0.0 - 11.5.99. Before it was 7.0.0 - 10.9.99.

The requirements in composer.json however didn't change since ages:

"require": {
    "typo3/cms-core": ">=7.0.0"
  },

This means that it was suitable for TYPO3 11 before 23/12/2021 and would be suitable for TYPO3 12 in the future, even if it might not be true.

Please narrow your requirements and set a maximum requirement version of the typo3 core. Systems rely on that and other extensions do it, too.

Cheers

**Comment by nitsan-technologies** [comment]
Hey!

We appreciate your reporting, we have corrected the dependencies and released the new version.

Cheers!
